services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: station-ski-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stationSki
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - station-ski-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  app:
    image: koussayblh/gestion-station-ski:latest
    pull_policy: always
    container_name: station-ski-app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /api
    ports:
      - "8089:8089"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - station-ski-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Angular Frontend
  frontend:
    image: devops-platform-frontend:latest
    pull_policy: never
    container_name: station-ski-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      app:
        condition: service_healthy
    networks:
      - station-ski-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mysql_data:

networks:
  station-ski-network:
    driver: bridge
